# Generated by Django 4.0.2 on 2022-03-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=70)),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=90)),
                ('village_post', models.CharField(max_length=90)),
                ('contact', models.CharField(max_length=10)),
            ],
        ),
    ]
