# Generated by Django 4.0.2 on 2022-03-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_image', models.ImageField(upload_to='product_image')),
                ('product_price', models.FloatField(max_length=100)),
                ('product_brand', models.CharField(max_length=70)),
                ('product_cat', models.CharField(max_length=80)),
                ('provider_id', models.IntegerField(max_length=80)),
            ],
        ),
    ]
