# Generated by Django 4.0.2 on 2022-04-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_product_info_provider_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_to_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField(max_length=100)),
                ('product_price', models.FloatField()),
                ('product_id', models.IntegerField()),
                ('who_is_to_add_id', models.IntegerField()),
            ],
        ),
    ]
