# Generated by Django 4.0.2 on 2022-04-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_add_to_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_contact', models.IntegerField()),
                ('to_contact', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='chat_messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_name', models.TextField()),
                ('from_id', models.IntegerField()),
                ('message', models.TextField()),
                ('to_name', models.TextField()),
                ('to_id', models.IntegerField()),
                ('time_of', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='add_to_cart',
            name='product_name',
            field=models.TextField(),
        ),
    ]
