# Generated by Django 4.0.2 on 2022-04-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_chat_contact_chat_messages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_contact',
            name='name_of_contact',
            field=models.TextField(default='sanjay'),
            preserve_default=False,
        ),
    ]
