# Generated by Django 4.0.2 on 2022-04-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_chat_contact_name_of_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_info',
            name='status',
            field=models.CharField(default='false', max_length=10),
            preserve_default=False,
        ),
    ]
