# Generated by Django 4.0.2 on 2022-04-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_product_info_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.IntegerField()),
                ('order_id', models.IntegerField()),
                ('signature', models.CharField(max_length=50)),
                ('product_id', models.IntegerField()),
                ('Buy_to_id', models.IntegerField()),
                ('sold_to_id', models.IntegerField()),
            ],
        ),
    ]
